services:
  postgres:
    image: postgres:latest
    container_name: tfg-postgres
    environment:
      POSTGRES_DB: tfg
      POSTGRES_PASSWORD: gersonandre
      POSTGRES_USER: tony
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
