
    create table aguinaldos (
        anio integer,
        fecha_calculo date,
        fecha_fin_periodo date,
        fecha_inicio_periodo date,
        fecha_pago date,
        monto_aguinaldo float(53),
        total_salarios_devengados float(53),
        id bigint generated by default as identity,
        id_empleado bigint,
        primary key (id)
    );

    create table asistencias (
        fecha_hora timestamp(6),
        id bigint generated by default as identity,
        id_empleado bigint,
        observaciones varchar(500),
        tipo_evento varchar(255) check (tipo_evento in ('ENTRADA','SALIDA')),
        primary key (id)
    );

    create table configuracion_renta (
        monto_maximo float(53),
        monto_minimo float(53),
        porcentaje float(53),
        id bigint generated by default as identity,
        primary key (id)
    );

    create table departamentos (
        id bigint generated by default as identity,
        nombre varchar(255),
        primary key (id)
    );

    create table direccion (
        id bigint generated by default as identity,
        canton varchar(255),
        distrito varchar(255),
        indicaciones varchar(255),
        provincia varchar(255),
        primary key (id)
    );

    create table empleados (
        cantidad_de_hijos integer,
        esta_activo boolean,
        esta_casado boolean,
        fecha_ingreso date,
        fecha_nacimiento date,
        salario_base float(53),
        saldo_vacaciones integer,
        id bigint generated by default as identity,
        id_departamento bigint,
        id_direccion bigint,
        id_puesto bigint,
        id_usuario bigint unique,
        cedula varchar(255),
        correo_personal varchar(255),
        cuenta_iban varchar(255),
        nombre varchar(255),
        primer_apellido varchar(255),
        segundo_apellido varchar(255),
        tipo_de_jornada varchar(255) check (tipo_de_jornada in ()),
        primary key (id)
    );

    create table evaluaciones_de_desempeno (
        empleado_id date,
        puntuacion_final float(53),
        id bigint generated by default as identity,
        id_empleado bigint,
        empleado_nombre varchar(255),
        observaciones varchar(255),
        plan_de_mejora varchar(255),
        primary key (id)
    );

    create table horas_extra (
        aprobado boolean,
        cantidad_de_horas integer,
        fecha_solicitud date,
        procesado boolean,
        id bigint generated by default as identity,
        id_empleado bigint,
        estado_solicitud varchar(255) check (estado_solicitud in ()),
        motivo varchar(255),
        tipo_tarifa varchar(255) check (tipo_tarifa in ()),
        primary key (id)
    );

    create table liquidaciones (
        fecha_entrada date,
        monto_aguinaldo_pendiente float(53),
        monto_cesantia float(53),
        monto_preaviso float(53),
        monto_vacaciones_pendientes float(53),
        total_liquidacion float(53),
        id bigint generated by default as identity,
        id_empleado bigint,
        motivo_salida varchar(255) check (motivo_salida in ()),
        primary key (id)
    );

    create table permisos (
        dias_totales integer,
        fecha_fin date,
        fecha_inicio date,
        id bigint generated by default as identity,
        id_empleado bigint,
        estado_solicitud varchar(255) check (estado_solicitud in ()),
        motivo varchar(255),
        tipo_permiso varchar(255) check (tipo_permiso in ()),
        url_documento_adjunto varchar(255),
        primary key (id)
    );

    create table planilla_detalle (
        cantidad_dias_feriados integer,
        deducciones_ccss_ivm float(53),
        deducciones_ccss_sem float(53),
        impuesto_de_renta float(53),
        monto_horas_extra float(53),
        monto_incapacidad float(53),
        otras_deducciones float(53),
        salario_base_periodo float(53),
        id bigint generated by default as identity,
        id_empleado bigint,
        id_encabezado_planilla bigint,
        primary key (id)
    );

    create table planilla_encabezado (
        fecha_fin_periodo date,
        fecha_inicio_periodo date,
        fecha_pago date,
        total_planilla_bruto float(53),
        total_planilla_neto float(53),
        id bigint generated by default as identity,
        estado_planilla varchar(255) check (estado_planilla in ()),
        primary key (id)
    );

    create table puestos (
        salario_minimo float(53),
        id bigint generated by default as identity,
        id_departamento bigint,
        nombre varchar(255),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        password varchar(255),
        role varchar(255) check (role in ('ADMIN','HR','JEFE','EMPLEADO')),
        username varchar(255) not null,
        primary key (id),
        unique (username)
    );

    alter table if exists aguinaldos 
       add constraint FKgmpa7m6vhwg50patbi3n8mqth 
       foreign key (id_empleado) 
       references empleados;

    alter table if exists asistencias 
       add constraint FKhovyoatphnlh8b9lj9ut6t901 
       foreign key (id_empleado) 
       references empleados;

    alter table if exists empleados 
       add constraint FKrnmesv4tqvbufe58d30ygfest 
       foreign key (id_departamento) 
       references departamentos;

    alter table if exists empleados 
       add constraint FK8vq54q1oiiok3p2id76xo0ddk 
       foreign key (id_direccion) 
       references direccion;

    alter table if exists empleados 
       add constraint FKo4xoq0jejxxqm32fhbp0g0fdd 
       foreign key (id_puesto) 
       references puestos;

    alter table if exists empleados 
       add constraint FKecnisrer9al1kn0kw8buidsif 
       foreign key (id_usuario) 
       references users;

    alter table if exists evaluaciones_de_desempeno 
       add constraint FKnvxe10k4cssn941gv48q7cm7w 
       foreign key (id_empleado) 
       references empleados;

    alter table if exists horas_extra 
       add constraint FK8mkiwinharx9i7hj8p9yqbpaf 
       foreign key (id_empleado) 
       references empleados;

    alter table if exists liquidaciones 
       add constraint FKpfd6ot1aedy2540gkkqlg0wnh 
       foreign key (id_empleado) 
       references empleados;

    alter table if exists permisos 
       add constraint FK8311xma9irtcef2p2cccaguyp 
       foreign key (id_empleado) 
       references empleados;

    alter table if exists planilla_detalle 
       add constraint FKo9nmpn51l27chuh3i1rusmdn9 
       foreign key (id_empleado) 
       references empleados;

    alter table if exists planilla_detalle 
       add constraint FK6ecsdxs48me8kq97utw2eoyx2 
       foreign key (id_encabezado_planilla) 
       references planilla_encabezado;

    alter table if exists puestos 
       add constraint FKh8fx4q4u3x6syw4wu0q3s93x9 
       foreign key (id_departamento) 
       references departamentos;

    create table aguinaldos (
        anio integer,
        fecha_calculo date,
        fecha_fin_periodo date,
        fecha_inicio_periodo date,
        fecha_pago date,
        monto_aguinaldo float(53),
        total_salarios_devengados float(53),
        id bigint generated by default as identity,
        id_empleado bigint,
        primary key (id)
    );

    create table asistencias (
        fecha_hora timestamp(6),
        id bigint generated by default as identity,
        id_empleado bigint,
        observaciones varchar(500),
        tipo_evento varchar(255) check (tipo_evento in ('ENTRADA','SALIDA')),
        primary key (id)
    );

    create table configuracion_renta (
        monto_maximo float(53),
        monto_minimo float(53),
        porcentaje float(53),
        id bigint generated by default as identity,
        primary key (id)
    );

    create table departamentos (
        id bigint generated by default as identity,
        nombre varchar(255),
        primary key (id)
    );

    create table direccion (
        id bigint generated by default as identity,
        canton varchar(255),
        distrito varchar(255),
        indicaciones varchar(255),
        provincia varchar(255),
        primary key (id)
    );

    create table empleados (
        cantidad_de_hijos integer,
        esta_activo boolean,
        esta_casado boolean,
        fecha_ingreso date,
        fecha_nacimiento date,
        salario_base float(53),
        saldo_vacaciones integer,
        id bigint generated by default as identity,
        id_departamento bigint,
        id_direccion bigint,
        id_puesto bigint,
        id_usuario bigint unique,
        cedula varchar(255),
        correo_personal varchar(255),
        cuenta_iban varchar(255),
        nombre varchar(255),
        primer_apellido varchar(255),
        segundo_apellido varchar(255),
        tipo_de_jornada varchar(255) check (tipo_de_jornada in ()),
        primary key (id)
    );

    create table evaluaciones_de_desempeno (
        empleado_id date,
        puntuacion_final float(53),
        id bigint generated by default as identity,
        id_empleado bigint,
        empleado_nombre varchar(255),
        observaciones varchar(255),
        plan_de_mejora varchar(255),
        primary key (id)
    );

    create table horas_extra (
        aprobado boolean,
        cantidad_de_horas integer,
        fecha_solicitud date,
        procesado boolean,
        id bigint generated by default as identity,
        id_empleado bigint,
        estado_solicitud varchar(255) check (estado_solicitud in ()),
        motivo varchar(255),
        tipo_tarifa varchar(255) check (tipo_tarifa in ()),
        primary key (id)
    );

    create table liquidaciones (
        fecha_entrada date,
        monto_aguinaldo_pendiente float(53),
        monto_cesantia float(53),
        monto_preaviso float(53),
        monto_vacaciones_pendientes float(53),
        total_liquidacion float(53),
        id bigint generated by default as identity,
        id_empleado bigint,
        motivo_salida varchar(255) check (motivo_salida in ()),
        primary key (id)
    );

    create table permisos (
        dias_totales integer,
        fecha_fin date,
        fecha_inicio date,
        id bigint generated by default as identity,
        id_empleado bigint,
        estado_solicitud varchar(255) check (estado_solicitud in ()),
        motivo varchar(255),
        tipo_permiso varchar(255) check (tipo_permiso in ()),
        url_documento_adjunto varchar(255),
        primary key (id)
    );

    create table planilla_detalle (
        cantidad_dias_feriados integer,
        deducciones_ccss_ivm float(53),
        deducciones_ccss_sem float(53),
        impuesto_de_renta float(53),
        monto_horas_extra float(53),
        monto_incapacidad float(53),
        otras_deducciones float(53),
        salario_base_periodo float(53),
        id bigint generated by default as identity,
        id_empleado bigint,
        id_encabezado_planilla bigint,
        primary key (id)
    );

    create table planilla_encabezado (
        fecha_fin_periodo date,
        fecha_inicio_periodo date,
        fecha_pago date,
        total_planilla_bruto float(53),
        total_planilla_neto float(53),
        id bigint generated by default as identity,
        estado_planilla varchar(255) check (estado_planilla in ()),
        primary key (id)
    );

    create table puestos (
        salario_minimo float(53),
        id bigint generated by default as identity,
        id_departamento bigint,
        nombre varchar(255),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        password varchar(255),
        role varchar(255) check (role in ('ADMIN','HR','JEFE','EMPLEADO')),
        username varchar(255) not null,
        primary key (id),
        unique (username)
    );

    alter table if exists aguinaldos 
       add constraint FKgmpa7m6vhwg50patbi3n8mqth 
       foreign key (id_empleado) 
       references empleados;

    alter table if exists asistencias 
       add constraint FKhovyoatphnlh8b9lj9ut6t901 
       foreign key (id_empleado) 
       references empleados;

    alter table if exists empleados 
       add constraint FKrnmesv4tqvbufe58d30ygfest 
       foreign key (id_departamento) 
       references departamentos;

    alter table if exists empleados 
       add constraint FK8vq54q1oiiok3p2id76xo0ddk 
       foreign key (id_direccion) 
       references direccion;

    alter table if exists empleados 
       add constraint FKo4xoq0jejxxqm32fhbp0g0fdd 
       foreign key (id_puesto) 
       references puestos;

    alter table if exists empleados 
       add constraint FKecnisrer9al1kn0kw8buidsif 
       foreign key (id_usuario) 
       references users;

    alter table if exists evaluaciones_de_desempeno 
       add constraint FKnvxe10k4cssn941gv48q7cm7w 
       foreign key (id_empleado) 
       references empleados;

    alter table if exists horas_extra 
       add constraint FK8mkiwinharx9i7hj8p9yqbpaf 
       foreign key (id_empleado) 
       references empleados;

    alter table if exists liquidaciones 
       add constraint FKpfd6ot1aedy2540gkkqlg0wnh 
       foreign key (id_empleado) 
       references empleados;

    alter table if exists permisos 
       add constraint FK8311xma9irtcef2p2cccaguyp 
       foreign key (id_empleado) 
       references empleados;

    alter table if exists planilla_detalle 
       add constraint FKo9nmpn51l27chuh3i1rusmdn9 
       foreign key (id_empleado) 
       references empleados;

    alter table if exists planilla_detalle 
       add constraint FK6ecsdxs48me8kq97utw2eoyx2 
       foreign key (id_encabezado_planilla) 
       references planilla_encabezado;

    alter table if exists puestos 
       add constraint FKh8fx4q4u3x6syw4wu0q3s93x9 
       foreign key (id_departamento) 
       references departamentos;

