-- Eliminar todas las tablas
DROP TABLE IF EXISTS aguinaldos CASCADE;
DROP TABLE IF EXISTS asistencias CASCADE;
DROP TABLE IF EXISTS configuracion_renta CASCADE;
DROP TABLE IF EXISTS departamentos CASCADE;
DROP TABLE IF EXISTS direccion CASCADE;
DROP TABLE IF EXISTS empleados CASCADE;
DROP TABLE IF EXISTS evaluaciones_de_desempeno CASCADE;
DROP TABLE IF EXISTS horas_extra CASCADE;
DROP TABLE IF EXISTS liquidaciones CASCADE;
DROP TABLE IF EXISTS permisos CASCADE;
DROP TABLE IF EXISTS planilla_detalle CASCADE;
DROP TABLE IF EXISTS planilla_encabezado CASCADE;
DROP TABLE IF EXISTS puestos CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- Crear todas las tablas
CREATE TABLE users (
    id bigint generated by default as identity,
    password varchar(255),
    role varchar(255) check (role in ('ADMIN','HR','JEFE','EMPLEADO')),
    username varchar(255) not null,
    primary key (id),
    unique (username)
);

CREATE TABLE departamentos (
    id bigint generated by default as identity,
    nombre varchar(255),
    primary key (id)
);

CREATE TABLE direccion (
    id bigint generated by default as identity,
    canton varchar(255),
    distrito varchar(255),
    indicaciones varchar(255),
    provincia varchar(255),
    primary key (id)
);

CREATE TABLE puestos (
    salario_minimo float(53),
    id bigint generated by default as identity,
    id_departamento bigint,
    nombre varchar(255),
    primary key (id)
);

CREATE TABLE empleados (
    cantidad_de_hijos integer,
    esta_activo boolean,
    esta_casado boolean,
    fecha_ingreso date,
    fecha_nacimiento date,
    salario_base float(53),
    saldo_vacaciones integer,
    id bigint generated by default as identity,
    id_departamento bigint,
    id_direccion bigint,
    id_puesto bigint,
    id_usuario bigint unique,
    cedula varchar(255),
    correo_personal varchar(255),
    cuenta_iban varchar(255),
    nombre varchar(255),
    primer_apellido varchar(255),
    segundo_apellido varchar(255),
    tipo_de_jornada varchar(255),
    primary key (id)
);

CREATE TABLE aguinaldos (
    anio integer,
    fecha_calculo date,
    fecha_fin_periodo date,
    fecha_inicio_periodo date,
    fecha_pago date,
    monto_aguinaldo float(53),
    total_salarios_devengados float(53),
    id bigint generated by default as identity,
    id_empleado bigint,
    primary key (id)
);

CREATE TABLE asistencias (
    fecha_hora timestamp(6),
    id bigint generated by default as identity,
    id_empleado bigint,
    observaciones varchar(500),
    tipo_evento varchar(255) check (tipo_evento in ('ENTRADA','SALIDA')),
    primary key (id)
);

CREATE TABLE configuracion_renta (
    monto_maximo float(53),
    monto_minimo float(53),
    porcentaje float(53),
    id bigint generated by default as identity,
    primary key (id)
);

CREATE TABLE evaluaciones_de_desempeno (
    empleado_id date,
    puntuacion_final float(53),
    id bigint generated by default as identity,
    id_empleado bigint,
    empleado_nombre varchar(255),
    observaciones varchar(255),
    plan_de_mejora varchar(255),
    primary key (id)
);

CREATE TABLE horas_extra (
    aprobado boolean,
    cantidad_de_horas integer,
    fecha_solicitud date,
    procesado boolean,
    id bigint generated by default as identity,
    id_empleado bigint,
    estado_solicitud varchar(255),
    motivo varchar(255),
    tipo_tarifa varchar(255),
    primary key (id)
);

CREATE TABLE jefes_departamento (
    esta_activo boolean,
    fecha_fin date,
    fecha_inicio date,
    id bigint generated by default as identity,
    id_departamento bigint,
    id_empleado bigint,
    primary key (id)
);

CREATE TABLE liquidaciones (
    fecha_entrada date,
    monto_aguinaldo_pendiente float(53),
    monto_cesantia float(53),
    monto_preaviso float(53),
    monto_vacaciones_pendientes float(53),
    total_liquidacion float(53),
    id bigint generated by default as identity,
    id_empleado bigint,
    motivo_salida varchar(255),
    primary key (id)
);

CREATE TABLE permisos (
    dias_totales integer,
    fecha_fin date,
    fecha_inicio date,
    fecha_solicitud date,
    fecha_aprobacion_jefe date,
    fecha_aprobacion_rh date,
    id bigint generated by default as identity,
    id_empleado bigint,
    id_aprobador_jefe bigint,
    id_aprobador_rh bigint,
    estado_solicitud varchar(255),
    motivo text,
    observaciones_empleado text,
    comentarios_jefe text,
    comentarios_rh text,
    tipo_permiso varchar(255),
    url_documento_adjunto varchar(255),
    primary key (id)
);

CREATE TABLE planilla_encabezado (
    fecha_fin_periodo date,
    fecha_inicio_periodo date,
    fecha_pago date,
    total_planilla_bruto float(53),
    total_planilla_neto float(53),
    id bigint generated by default as identity,
    estado_planilla varchar(255),
    primary key (id)
);

CREATE TABLE planilla_detalle (
    cantidad_dias_feriados integer,
    deducciones_ccss_ivm float(53),
    deducciones_ccss_sem float(53),
    impuesto_de_renta float(53),
    monto_horas_extra float(53),
    monto_incapacidad float(53),
    otras_deducciones float(53),
    salario_base_periodo float(53),
    id bigint generated by default as identity,
    id_empleado bigint,
    id_encabezado_planilla bigint,
    primary key (id)
);

-- Agregar foreign keys
ALTER TABLE puestos 
   ADD CONSTRAINT FKh8fx4q4u3x6syw4wu0q3s93x9 
   FOREIGN KEY (id_departamento) 
   REFERENCES departamentos;

ALTER TABLE empleados 
   ADD CONSTRAINT FKrnmesv4tqvbufe58d30ygfest 
   FOREIGN KEY (id_departamento) 
   REFERENCES departamentos;

ALTER TABLE empleados 
   ADD CONSTRAINT FK8vq54q1oiiok3p2id76xo0ddk 
   FOREIGN KEY (id_direccion) 
   REFERENCES direccion;

ALTER TABLE empleados 
   ADD CONSTRAINT FKo4xoq0jejxxqm32fhbp0g0fdd 
   FOREIGN KEY (id_puesto) 
   REFERENCES puestos;

ALTER TABLE empleados 
   ADD CONSTRAINT FKecnisrer9al1kn0kw8buidsif 
   FOREIGN KEY (id_usuario) 
   REFERENCES users;

ALTER TABLE aguinaldos 
   ADD CONSTRAINT FKgmpa7m6vhwg50patbi3n8mqth 
   FOREIGN KEY (id_empleado) 
   REFERENCES empleados;

ALTER TABLE asistencias 
   ADD CONSTRAINT FKhovyoatphnlh8b9lj9ut6t901 
   FOREIGN KEY (id_empleado) 
   REFERENCES empleados;

ALTER TABLE evaluaciones_de_desempeno 
   ADD CONSTRAINT FKnvxe10k4cssn941gv48q7cm7w 
   FOREIGN KEY (id_empleado) 
   REFERENCES empleados;

ALTER TABLE horas_extra 
   ADD CONSTRAINT FK8mkiwinharx9i7hj8p9yqbpaf 
   FOREIGN KEY (id_empleado) 
   REFERENCES empleados;

ALTER TABLE jefes_departamento 
   ADD CONSTRAINT FKjefes_depto_departamento 
   FOREIGN KEY (id_departamento) 
   REFERENCES departamentos;

ALTER TABLE jefes_departamento 
   ADD CONSTRAINT FKjefes_depto_empleado 
   FOREIGN KEY (id_empleado) 
   REFERENCES empleados;

ALTER TABLE liquidaciones 
   ADD CONSTRAINT FKpfd6ot1aedy2540gkkqlg0wnh 
   FOREIGN KEY (id_empleado) 
   REFERENCES empleados;

ALTER TABLE permisos 
   ADD CONSTRAINT FK8311xma9irtcef2p2cccaguyp 
   FOREIGN KEY (id_empleado) 
   REFERENCES empleados;

ALTER TABLE planilla_detalle 
   ADD CONSTRAINT FKo9nmpn51l27chuh3i1rusmdn9 
   FOREIGN KEY (id_empleado) 
   REFERENCES empleados;

ALTER TABLE planilla_detalle 
   ADD CONSTRAINT FK6ecsdxs48me8kq97utw2eoyx2 
   FOREIGN KEY (id_encabezado_planilla) 
   REFERENCES planilla_encabezado;
