spring.application.name=tfg
application.title = Sistema de Gestion de RH para la sastreria Gerson Andre
spring.application.version = 1.0.0

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql= true

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url = jdbc:postgresql://localhost:5432/tfg
spring.datasource.username=tony
spring.datasource.password=gersonandre

jwt.secret = rceEl9OFPkaSAWQv0hh66KZ0W9lhh1uL8J6DI6ff46Q=

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

logging.file.name=logs/app.log
